export {};

declare global {
  var MOVES: Record<string, MoveData>;
  var Moves: Record<string, MoveData>;
  var POKEDEX: Record<string, any>;
  var ITEMS: Record<string, any>;
  var TYPE_CHART: Record<string, any>;
  var NATURE_MODIFIERS: Record<string, any>;
  var AbilityHandlers: Record<string, any>;
  var MoveHandlers: Record<string, MoveHandler>;
  var MoveEffects: Record<string, any>;
  var ItemEffects: Record<string, any>;
  var FORM_SUFFIXES: string[];
  var FALLBACK_MOVES: string[];
  var DRAIN_MOVES: Record<string, [number, number]>;
  var RECOIL_MOVES: Record<string, [number, number]>;
  var battle: BattleStateLike | null;
  var Pokemon: new (...args: any[]) => PokemonLike;
  var module: any;

  function getMoveHandler(moveName: string): MoveHandler | null;
  function hasMoveHandler(moveName: string): boolean;
  function getChargeMoveConfig(moveName: string): Record<string, any> | null;
  function applyDamage(attacker: PokemonLike, defender: PokemonLike, move: MoveData, spriteIdRef: string): DamageResult;
  function applyMoveSecondaryEffects(user: PokemonLike, target: PokemonLike, move: MoveData, damageDealt?: number, battle?: BattleStateLike | null, isPlayer?: boolean): Record<string, any>;
  function checkInvulnerability(...args: any[]): Record<string, any> | null;
  function getTypeEffectiveness(atkType: string, defTypes: string[] | string, moveName?: string): number;
  function updateEvolutionButtonVisuals(pokemon?: PokemonLike): void;
  function updateStyleButtonCooldown(): void;
  function clearChargingState(pokemon: PokemonLike): void;
  function autoDetectMegaEligibility(pokemon: PokemonLike, configuredMega?: string | null): void;
  function isSwappable(user: PokemonLike, target?: PokemonLike, battle?: BattleStateLike | null): boolean;
  function getItem(name: string): Record<string, any> | null;
  function setWeatherVisuals(weather: string | null): void;
  function removeTeraCrown(side: 'player' | 'enemy' | string): void;
  function renderSwitchMenu(canCancel?: boolean): void;
  function battleEndSequence(result: 'win' | 'loss' | string): void;
  function handleAttack(...args: any[]): Promise<any> | any;
  function executeEndPhase(player: PokemonLike, enemy: PokemonLike): Promise<any> | any;
  function markEnemySwitch(): void;
  function smartLoadSprite(elementId: string, spriteUrl: string, isPlayer?: boolean): Promise<any> | any;
  function playPokemonCry(pokemonName: string): void;
  function checkCrisisBgm(): void;
  function checkInitTransform(pokemon: PokemonLike): Record<string, any> | null;
  function triggerEntryAbilities(pokemon: PokemonLike, opponent: PokemonLike): void;
  function handlePlayerFainted(pokemon: PokemonLike): Promise<any> | any;
  function getAiAction(aiPoke: PokemonLike, playerPoke: PokemonLike, difficulty?: string, aiParty?: PokemonLike[], battleContext?: AiBattleContext): AiAction | null;
  function getAiMove(attacker: PokemonLike, defender: PokemonLike, difficulty?: string): MoveData | null;
  function applyDynamaxState(pokemon: PokemonLike, active: boolean): void;
  function endDynamaxAnimation(pokemon: PokemonLike, isPlayer?: boolean): Promise<any> | any;
  function canMegaEvolve(pokemon: PokemonLike, unlocks?: Record<string, any>): boolean;
  function checkBattleBondTransform(pokemon: PokemonLike): Record<string, any> | null;
  function autoProcessNecrozmaFusion(party: PokemonLike[], logFn?: (message: string) => void): Record<string, any>;
  function getMovePriority(move: MoveData, user?: PokemonLike, target?: PokemonLike): number;
  function triggerBerryEffect(pokemon: PokemonLike, berryOrBattle?: string | BattleStateLike | null, logs?: string[]): string[] | void;
  function log(message: string): void;
  function updateAllVisuals(forceSpriteAnim?: boolean | string): void;

  interface Window {
    battle?: BattleStateLike | null;
    MOVES?: Record<string, MoveData>;
    Moves?: Record<string, MoveData>;
    POKEDEX?: Record<string, any>;
    ITEMS?: Record<string, any>;
    TYPE_CHART?: Record<string, any>;
    NATURE_MODIFIERS?: Record<string, any>;
    AbilityHandlers?: Record<string, any>;
    MoveHandlers?: Record<string, MoveHandler>;
    MoveEffects?: Record<string, any>;
    WeatherEffects?: Record<string, any>;
    ItemEffects?: Record<string, any>;
    BattleVFX?: Record<string, any>;
    PPSystem?: PPSystemLike;
    envOverlay?: Record<string, any>;
    Locale?: { get(name: string): string };
    GAME_SETTINGS?: Record<string, any>;
    CHARGE_MOVES?: Record<string, any>;
    calcDamage?: (attacker: PokemonLike, defender: PokemonLike, move: MoveData, options?: Record<string, any>) => DamageResult;
    applyDamage?: (attacker: PokemonLike, defender: PokemonLike, move: MoveData, spriteIdRef: string) => DamageResult;
    applyMoveSecondaryEffects?: (user: PokemonLike, target: PokemonLike, move: MoveData, damageDealt?: number, battle?: BattleStateLike | null, isPlayer?: boolean) => Record<string, any>;
    getMoveHandler?: (moveName: string) => MoveHandler | null;
    hasMoveHandler?: (moveName: string) => boolean;
    getTypeEffectiveness?: (atkType: string, defTypes: string[], moveName?: string) => number;
    getPokemonData?: (name: string) => Record<string, any> | null;
    getMoveData?: (name: string) => MoveData | null;
    calcStats?: (baseStats: StatTable, level: number, options?: Record<string, any>) => StatTable;
    Pokemon?: new (...args: any[]) => PokemonLike;
    BattleState?: new (...args: any[]) => BattleStateLike;
    checkCanMove?: (pokemon: PokemonLike, move?: MoveData | null) => Record<string, any>;
    checkCanSwitch?: (pokemon: PokemonLike, opponent?: PokemonLike, battle?: BattleStateLike | null) => SwitchFlowResult;
    clearVolatileStatus?: (pokemon: PokemonLike) => void;
    clearAllVolatileStatus?: (pokemon: PokemonLike) => void;
    playSFX?: (id: string) => void;
    playHitSFX?: (effectiveness?: number, isCrit?: boolean) => void;
    updateAllVisuals?: (forceSpriteAnim?: boolean | string) => void;
    updateBattleSprites?: () => void;
    log?: (message: string) => void;
    getItem?: (name: string) => Record<string, any> | null;
    isChoiceItem?: (name: string) => boolean;
    isBerry?: (name: string) => boolean;
    consumeItem?: (pokemon: PokemonLike, battle?: BattleStateLike | null) => string[];
    checkFocusPunchInterrupt?: (pokemon: PokemonLike, damageTaken: number) => boolean;
    clearChargingState?: (pokemon: PokemonLike) => void;
    renderSwitchMenu?: (canCancel?: boolean) => void;
    battleEndSequence?: (result: 'win' | 'loss' | string) => void;
    handleAttack?: (...args: any[]) => Promise<any> | any;
    executeEndPhase?: (player: PokemonLike, enemy: PokemonLike) => Promise<any> | any;
    markEnemySwitch?: () => void;
    smartLoadSprite?: (elementId: string, spriteUrl: string, isPlayer?: boolean) => Promise<any> | any;
    playPokemonCry?: (pokemonName: string) => void;
    checkCrisisBgm?: () => void;
    checkInitTransform?: (pokemon: PokemonLike) => Record<string, any> | null;
    triggerEntryAbilities?: (pokemon: PokemonLike, opponent: PokemonLike) => void;
    handlePlayerFainted?: (pokemon: PokemonLike) => Promise<any> | any;
    getAiAction?: (aiPoke: PokemonLike, playerPoke: PokemonLike, difficulty?: string, aiParty?: PokemonLike[], battleContext?: AiBattleContext) => AiAction | null;
    getAiMove?: (attacker: PokemonLike, defender: PokemonLike, difficulty?: string) => MoveData | null;
    applyDynamaxState?: (pokemon: PokemonLike, active: boolean) => void;
    endDynamaxAnimation?: (pokemon: PokemonLike, isPlayer?: boolean) => Promise<any> | any;
    canMegaEvolve?: (pokemon: PokemonLike, unlocks?: Record<string, any>) => boolean;
    checkBattleBondTransform?: (pokemon: PokemonLike) => Record<string, any> | null;
    autoProcessNecrozmaFusion?: (party: PokemonLike[], logFn?: (message: string) => void) => Record<string, any>;
    updateStyleButtonCooldown?: () => void;
    getMovePriority?: (move: MoveData, user?: PokemonLike, target?: PokemonLike) => number;
    triggerBerryEffect?: (pokemon: PokemonLike, berryOrBattle?: string | BattleStateLike | null, logs?: string[]) => string[] | void;
    checkBeakBlastBurn?: (pokemon: PokemonLike, attacker: PokemonLike, move: MoveData, logs: string[]) => boolean;
    getBestRevengeKiller?: (party: PokemonLike[], playerPokemon: PokemonLike, activeIndex: number) => number;
    setWeatherVisuals?: (weather: string) => void;
    resolveSpriteId?: (name: string) => string;
    extractBaseFormId?: (name: string) => string;
    getFallbackSpriteId?: (name: string) => string;
    [key: string]: any;
  }
}
